language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install git gcc-4.8 g++-4.8 debhelper devscripts gnupg python binutils-gold python-software-properties
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - wget https://raw.githubusercontent.com/vgvassilev/cling/master/tools/packaging/cpt.py
  - chmod +x cpt.py

before_script:
  # Perform a sanity check before proceeding
  - echo "no" | ./cpt.py -c

script:
  # FIXME: Change URLs to the repo of @vgvassilev after repositories have been updated.
  # Remove --no-test option when appropriate.
  - ./cpt.py --create-dev-env=release --no-test --with-llvm-url=https://github.com/onyb/llvm --with-clang-url=https://github.com/onyb/clang --with-cling-url=http://root.cern.ch/git/cling.git

branches:
  only:
    - master

notifications:
  recipients:
    - vvasilev@cern.ch
    - ani07nov@gmail.com
    #- cling-dev@cern.ch
  email:
    on_success: change
    on_failure: always

  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

os:
  - linux